# Generated by Django 5.0.1 on 2024-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='detail',
        ),
        migrations.AddField(
            model_name='news',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='newsapp.tag'),
        ),
        migrations.AddField(
            model_name='news',
            name='topics',
            field=models.ManyToManyField(to='newsapp.topic'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
