# Generated by Django 5.0.1 on 2024-01-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_tag_topic_remove_news_category_remove_news_add_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='newsAgency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsapp.newsagency'),
            preserve_default=False,
        ),
    ]
