# Generated by Django 5.0.1 on 2024-02-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_news_newsagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsAgency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.newsagency'),
        ),
    ]
