# Generated by Django 5.0.1 on 2024-06-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_remove_news_tags_remove_news_topics_delete_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='topics',
            new_name='topic',
        ),
    ]
