# Generated by Django 5.0.6 on 2024-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_rename_topics_news_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
