# Generated by Django 5.1 on 2024-08-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.IntegerField(null=True),
        ),
    ]
