# Generated by Django 5.1 on 2024-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='token',
            field=models.CharField(default='2e409f1b43804a87ae0a566ac1adec89', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='iframe',
            name='token',
            field=models.CharField(default='23572fe0e3d141f0b384fb14fd28f36d', max_length=1000, unique=True),
        ),
    ]
