# Generated by Django 5.1 on 2024-09-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_alter_api_token_alter_iframe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='token',
            field=models.CharField(default='c22abe904ecc409a89fbc2bd50455222', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='iframe',
            name='token',
            field=models.CharField(default='5cc1aac662b04f4a889f4bbda4c89d80', max_length=1000, unique=True),
        ),
    ]
