# Generated by Django 5.1 on 2024-09-26 19:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_alter_api_token_alter_iframe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='iframe',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
